version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

# Load testing (optional)
#  k6:
#    image: grafana/k6:latest
#    working_dir: /scripts
#    volumes:
#      - ./k6:/scripts
#    network_mode: bridge
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    command: run claim.js

volumes:
  mariadb_data:
